[project]
name = "bib_bot"
version = "1.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bibtexparser>=2.0.0b8",
    "slack-bolt>=1.27.0",
    "titlecase>=2.4.1",
]
